name: "create ami for prod"

on:
  push:
    branches:
      - prod

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      packer_version: "1.9.4"

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3

      - name: "Setup packer"
        uses: hashicorp/setup-packer@main
        with:
          version: ${{ env.PACKER_VERSION }} 

      - name: "packer init"
        run: packer init .
        working-directory: ./packer/

      - name: "packer validate"
        run: packer validate -var-file="prod.pkrvars.hcl" . 
        working-directory: ./packer/

      - name: "packer-formating"
        run: packer fmt .
        working-directory: ./packer/

      - name: "building image"
        run: packer build -var-file="prod.pkrvars.hcl" .
        working-directory: ./packer/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.PROD_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_SECRET_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.PROD_REGION }}

      - name: "Notify Dev Deploy"
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT }}
          repository: vishnugout/shopping-app-infra28
          event-type: prod-deploy-event      
